openapi: 3.0.0
info:
  title: Comics Book API
  description: This is API for comics book store
  version: 1.0.0
paths:
  /products:
    get:
      summary: get list of books
      description: |
        Get list of all comics books
      operationId: getProducts
      responses:
        "200":
          description: Found results
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
  /products/{productId}:
    get:
      summary: Delete city
      description: Delete city by ID
      parameters:
      - name: productId
        in: path
        description: ID of product.
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Found book
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        "404":
          description: Not found book
components:
  schemas:
    Product:
      required:
      - id
      - title
      type: object
      properties:
        id:
          type: string
          example: 1
        title:
          type: string
          example: V for Vandetta
        price:
          type: number
          example: 15.17
        author:
          type: string
          example: Alan Moore
        published:
          type: string
          example: 2008
        img:
          type: string
          example: https://some-url
